// Token Ids generated by 'dev dfa' tool (DO NOT EDIT BELOW)
const T_INT: i32 = 0;
const T_DBL: i32 = 1;
const T_LBL: i32 = 2;
const T_ID: i32 = 3;
const T_ASSIGN: i32 = 4;
const T_EQUIV: i32 = 5;
const T_IF: i32 = 6;
const T_DO: i32 = 7;
const T_BROP: i32 = 8;
const T_BRCL: i32 = 9;
// End of token Ids generated by 'dev dfa' tool (DO NOT EDIT ABOVE)
